/*
 * This source file was generated by the Gradle 'init' task
 */
package ribsjdbc;

import ribsjdbc.utilities.ConfigManager;

public class App {
    public static void main(String[] args) {
        ConfigManager.checkAndCreateConfig();
        EmployeeRedactor employeeRedactor = new EmployeeRedactor();
        employeeRedactor.start();
    }
}
        
